sudo: required
services: 
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin  
  - docker build -t rohansawant/tcsca-api ./api
  - docker build -t rohansawant/tcsca-client --file ./client/Dockerfile-prod ./client
  - docker build -t rohansawant/tcsca-database ./database
  - docker build -t rohansawant/tcsca-proxy --file ./proxy/Dockerfile-prod ./proxy
  - docker build -t rohansawant/tcsca-redis ./redis
  - docker build -t rohansawant/tcsca-worker --file ./worker/Dockerfile .

  - docker push rohansawant/tcsca-api
  - docker push rohansawant/tcsca-client
  - docker push rohansawant/tcsca-database
  - docker push rohansawant/tcsca-proxy
  - docker push rohansawant/tcsca-redis
  - docker push rohansawant/tcsca-worker