version: "3.3"

services:
  proxy:
    container_name: proxy
    build: 
      context: proxy/.
      dockerfile: Dockerfile-prod
    ports:
      - 80:80
    restart: on-failure:10

  database:
    container_name: database
    build: database/.
    volumes:
      - ./database/db_data:/var/lib/postgresql
    env_file:
      - .env

  client:
    container_name: client
    build: 
      context: client/.
      dockerfile: Dockerfile-prod
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    stdin_open: true

  api:
    container_name: api
    build: api/.
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./api:/app

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    env_file:
      - .env

  redis:
    container_name: redis
    build: redis/.
    env_file:
      - .env

