apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: rohansawant/tcsca-api
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
            - name: POSTGRES_USER
              value: user
            - name: DBHOST
              value: database-cluster-ip-service
            - name: DBPORT
              value: "5432"
            - name: POSTGRES_DB
              value: anno_db
            - name: POSTGRES_PASSWORD
              value: hardpassword